//! Raw FFI bindings generated by bindgen from `c/engine.h`.
//!
//! These bindings are auto-generated at build time. This module re-exports them
//! and should not be used directly by consumers of this crate.

#![allow(non_upper_case_globals)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(dead_code)]
#![allow(clippy::all)]

include!(concat!(env!("OUT_DIR"), "/bindings.rs"));
